# Generated by Django 4.2.4 on 2023-11-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nim', models.IntegerField()),
                ('alamat', models.CharField(max_length=200)),
                ('prody', models.CharField(max_length=200)),
                ('jurusan', models.CharField(max_length=200)),
            ],
        ),
    ]
